import { FinancialResult } from "@/types/financial";

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function generateTextReport(result: FinancialResult): string {
  const actionPlanText = result.actionPlan
    .map((action, index) => `${index + 1}. ${action}`)
    .join("\n");

  return `
FInsight Financial Report
Generated by FInsight

----------------------------------------
FINANCIAL READINESS SCORE
----------------------------------------

Overall Score: ${result.score.totalScore} / 100

Emergency Fund Score: ${result.score.emergencyFundScore} / 25
Debt Health Score: ${result.score.debtHealthScore} / 25
Asset Strength Score: ${result.score.assetStrengthScore} / 25
Goal Fit Score: ${result.score.goalFitScore} / 25

----------------------------------------
FINANCIAL SNAPSHOT
----------------------------------------

Income Present Value: ${formatCurrency(result.incomePV)}
Asset Value: ${formatCurrency(result.assetValue)}
Debt Present Value: ${formatCurrency(result.debtPV)}
Expense Present Value: ${formatCurrency(result.expensePV)}
Net Position: ${formatCurrency(result.netPosition)}

----------------------------------------
RECOMMENDATION
----------------------------------------

${result.recommendation}

----------------------------------------
PRIORITY ACTION PLAN
----------------------------------------

${actionPlanText}

----------------------------------------
SCENARIO COMPARISON
----------------------------------------

Current Plan Net Position: ${formatCurrency(
    result.scenarioComparison.currentNetPosition
  )}
Improved Plan Net Position: ${formatCurrency(
    result.scenarioComparison.improvedNetPosition
  )}
Difference: ${formatCurrency(result.scenarioComparison.difference)}

${result.scenarioComparison.summary}

----------------------------------------
DISCLAIMER
----------------------------------------

FInsight is for educational purposes only and does not provide financial, investment, tax, or legal advice.
`.trim();
}

export function downloadTextReport(result: FinancialResult) {
  const report = generateTextReport(result);

  const blob = new Blob([report], {
    type: "text/plain;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = "finsight-financial-report.txt";
  link.click();

  URL.revokeObjectURL(url);
}