import { FinancialResult } from "@/types/financial";

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function generateTextReport(result: FinancialResult): string {
  const actionPlanText = result.actionPlan
    .map((action, index) => `${index + 1}. ${action}`)
    .join("\n");

  return `
FInsight Financial Report
Generated by FInsight

----------------------------------------
FINANCIAL READINESS SCORE
----------------------------------------

Overall Score: ${result.score.totalScore} / 100

Emergency Fund Score: ${result.score.emergencyFundScore} / 25
Debt Health Score: ${result.score.debtHealthScore} / 25
Asset Strength Score: ${result.score.assetStrengthScore} / 25
Goal Fit Score: ${result.score.goalFitScore} / 25

----------------------------------------
FINANCIAL SNAPSHOT
----------------------------------------

Income Present Value: ${formatCurrency(result.incomePV)}
Asset Value: ${formatCurrency(result.assetValue)}
Debt Present Value: ${formatCurrency(result.debtPV)}
Expense Present Value: ${formatCurrency(result.expensePV)}
Net Position: ${formatCurrency(result.netPosition)}

----------------------------------------
RECOMMENDATION
----------------------------------------

${result.recommendation}

----------------------------------------
PRIORITY ACTION PLAN
----------------------------------------

${actionPlanText}

----------------------------------------
SCENARIO COMPARISON
----------------------------------------

Current Plan Net Position: ${formatCurrency(
    result.scenarioComparison.currentNetPosition
  )}
Improved Plan Net Position: ${formatCurrency(
    result.scenarioComparison.improvedNetPosition
  )}
Difference: ${formatCurrency(result.scenarioComparison.difference)}

${result.scenarioComparison.summary}
----------------------------------------
BUY VS RENT NPV MODEL
----------------------------------------

PV Cost of Renting: ${formatCurrency(result.buyRentAnalysis.rentPV)}
PV Cost of Buying: ${formatCurrency(result.buyRentAnalysis.buyPV)}
NPV Difference: ${formatCurrency(result.buyRentAnalysis.difference)}
Recommendation: ${result.buyRentAnalysis.recommendation.toUpperCase()}

${result.buyRentAnalysis.summary}
----------------------------------------
MONTE CARLO SIMULATION
----------------------------------------

Simulations Run: ${result.monteCarloResult.simulations}
Probability of Positive Net Position: ${(
    result.monteCarloResult.probabilityPositive * 100
  ).toFixed(0)}%

10th Percentile Net Position: ${formatCurrency(
    result.monteCarloResult.tenthPercentile
  )}
Median Net Position: ${formatCurrency(result.monteCarloResult.median)}
90th Percentile Net Position: ${formatCurrency(
    result.monteCarloResult.ninetiethPercentile
  )}

Average Net Position: ${formatCurrency(
    result.monteCarloResult.averageNetPosition
  )}
Worst Case: ${formatCurrency(result.monteCarloResult.worstCase)}
Best Case: ${formatCurrency(result.monteCarloResult.bestCase)}
----------------------------------------
MODEL METHODOLOGY
----------------------------------------

Core Net Position Formula:
Net Position = Income PV + Current Assets − Debt PV − Expense PV

Income Present Value:
Income PV = Sum of projected future income discounted back to present value.

Debt Present Value:
Debt PV = Payment × [1 − (1 + r)^−n] / r

Financial Readiness Score:
Score = Emergency Fund Score + Debt Health Score + Asset Strength Score + Goal Fit Score

Sensitivity Analysis:
The model tests net position around the user's selected income growth and discount rate assumptions.

Monte Carlo Simulation:
The model runs a user-selected number of randomized simulations by varying income growth, discount rate, investment return, and expense growth.

Key Default Assumptions:
- Default discount rate: 5%, adjustable by user
- Default base income growth: 2%, adjustable by user
- Default expense growth / inflation rate: 2.5%, adjustable by user
- Default expected investment return: 6%, adjustable by user
- Default Monte Carlo trials: 1,000, adjustable by user
- Emergency fund target: 3 months of expenses
- High-interest debt threshold: 15% APR

Limitations:
- Does not include taxes
- Does not use live market data
- Does not include exact mortgage amortization
- Uses simplified assumptions for educational purposes
- Does not provide financial, legal, tax, or investment advice
----------------------------------------
DISCLAIMER
----------------------------------------

FInsight is for educational purposes only and does not provide financial, investment, tax, or legal advice.
`.trim();
}

export function downloadTextReport(result: FinancialResult) {
  const report = generateTextReport(result);

  const blob = new Blob([report], {
    type: "text/plain;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = "finsight-financial-report.txt";
  link.click();

  URL.revokeObjectURL(url);
}